config/routes.rb
Rails.application.routes.draw do
  get 'verification_code/new'
  post 'verification_code/create'

  get 'auth/new'
  post 'auth/create'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attribute :phone_number
  attribute :name

  validates :phone_number, presence: true, phony_plausible: true
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  AuthenticationError = Class.new StandardError

  rescue_from AuthenticationError do |_|
    redirect_to(verification_code_new_path)
  end

  def authenticate_user!
    user_name = session[:user]
    token = session[:token]
    found_token = TokenDb.new.fetch(user_name: user_name)
    raise AuthenticationError unless [token, found_token].all? && found_token == token
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  include AuthHelper

  def create
    if verified?
      clear_verification_code
      session[:token] = new_token
      session[:user] = user.name
      redirect_to user_path(user.id)
    else
      redirect_to auth_new_path
    end
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i(new create)
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :phone_number)
  end
end

app/controllers/verification_code_controller.rb
class VerificationCodeController < ApplicationController
  include VerificationCodeHelper

  def new
  end

  def create
    if valid_user?
      generate_code
      redirect_to auth_new_path, flash: {
        notice: "When a text message with your verification code arrives, enter it here to log in"
      }
    else
      redirect_to verification_code_new_path, flash: {
        errors: ['The phone number and user name you entered do not match']
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
  def clear_verification_code
    verification_db.delete user_name: user.name
  end

  def verified?
    return unless user
    verification_db.fetch(user_name: user.name) == verification_code
  end

  def user
    User.where(name: user_name).first
  end

  def user_name
    auth_params[:name]
  end

  def verification_code
    auth_params[:verification_code]
  end

  def auth_params
    @auth_params ||= params.require(:auth).
      permit(:name, :verification_code)
  end

  def new_token
    token_db.create user_name: user.name
  end

  def verification_db
    VerificationCodeDb.new
  end

  def token_db
    TokenDb.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/verification_code_helper.rb
module VerificationCodeHelper
  def valid_user?
    User.where(name: user_name, phone_number: phone_number).any?
  end

  def generate_code
    db.create user_name: user_name
  end

  def user_name
    code_params[:name]
  end

  def phone_number
    code_params[:phone_number]
  end

  def code_params
    @code_params ||= params.require(:verification_code).
      permit(:name, :phone_number)
  end

  def db
    VerificationCodeDb.new
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Logins</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.phone_number %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/verification_code/create.html.erb
<h1>VerificationCode#create</h1>
<p>Find me in app/views/verification_code/create.html.erb</p>

app/views/verification_code/new.html.erb
<h1>Verification Code Request</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :verification_code, url: verification_code_create_path do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :phone_number %>
      <%= f.text_field :phone_number , class: 'form-control'%>

      <%= f.submit 'Request Verification Code', class: 'btn btn-primary' %>
    <% end %>
  </div>

  <div>
    <p>New? <%= link_to 'Sign Up!', new_user_path %></p>
  </div>
</div>